FROM ubuntu:22.04
RUN apt update

# Install linux dependencies
RUN apt install -y libarchive-dev libgomp1 libglu1-mesa-dev ocl-icd-opencl-dev curl

# Install specific node and npm by using nvm
ENV NODE_VERSION v18.18.2
ENV NVM_DIR /usr/local/nvm
ENV NODE_PATH $NVM_DIR/$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/$NODE_VERSION/bin:$PATH
RUN mkdir $NVM_DIR
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
RUN echo "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION && nvm alias default $NODE_VERSION && nvm use default" | bash

# Install ClassCAD
RUN mkdir -p /classcad
WORKDIR /classcad
RUN npm init -y

# x64
# RUN npm i @classcad/linux-x64@0.0.7-beta.2
# RUN chmod +x ./node_modules/@classcad/linux-x64/ClassCADInstance

# arm64, if you are on arm64, delete the x64 lines and activate the following lines
RUN npm i @classcad/linux-arm64@0.0.7-beta.3
RUN chmod +x ./node_modules/@classcad/linux-arm64/ClassCADInstance

# Copy the .ccapp downloaded from buerli.io.
# Replace <PATH-TO-CCAPP-FILE> with the path pointing to the downloaded .ccapp file.
COPY modeling.ccapp modeling.ccapp

# Start the server
EXPOSE 9091/tcp
CMD npx classcad --ip 0.0.0.0 --port 9091 --instances 2 --ccappfile modeling.ccapp