version: "3.5"

services:
  server:
    build:
      context: ./
      dockerfile: dockerfile
    image: buerli/server
    container_name: buerli-server
    tty: true
    stdin_open: true
    ports:
      - 9091:9091
    restart: unless-stopped
networks:
  default:
    name: buerli-server